import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/layout/main-header";
import SiteFooter from "@/components/layout/site-footer";
import React from "react";

const inter = Inter ({
  subsets: ['cyrillic'],
  variable: '--font-inter'
})

const roboto = Roboto ({
  subsets: ['cyrillic'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="ru" className={ `${inter.variable} ${roboto.variable}`}>
      <body>
        <main className="min-h-screen">
          <MainHeader />
          {children}
          <SiteFooter />
        </main>
      </body>
    </html>
  )
}